### ISSUE TITLE
What license is this code under?

### ISSUE THREAD

**Issue by siddharthist** [ccll/terraform-provider-virtualbox#3]
Please be aware that without a license, it is very difficult for others to legally use or reproduce your code. I'd recommand Apache v2 if you're not sure what license to choose.

**Comment by jzohrab** [comment]
Good call.  @ccll - There are other license choices.  Ref http://choosealicense.com/.  The MIT and Apache licenses both have "how to apply this license" explanations.

**Comment by cr7pt0gr4ph7** [comment]
+1. I'd also be interested in using this, but are currently prevented from doing so due to the unknown license conditions.

**Comment by ccll** [comment]
Added a MIT license, please feel free to hack on it.
